export const HOME_BANNER = '/banner/1/en'
export const CONTACT ='/website/contact'
export const LOGO = '/v1/website/style'
export const PARTNERS = '/api/v1/topics/9/page/1/count/4/en'
export const PRESS_RELEASE = '/api/v1/topics/3/page/1/count/4/en'
export const SERVICE = '/api/v1/topics/2/page/1/count/4/en'
