export const HOME_BANNER = '/api/v1/banner/1/en'
export const CONTACT ='/api/v1/website/contacts'
export const LOGO = '/api/v1/website/style'
export const PARTNERS = '/api/v1/topics/9/page/1/count/4/en'
export const PRESS_RELEASE = '/api/v1/topics/3/page/1/count/4/en'
export const SERVICE = '/api/v1/topics/2/page/1/count/3/en'
export const ABOUT_US = '/api/v1/topics/1/page/1/count/7/en'
export const ABOUT_US_DETAILS = '/api/v1/topic'
